services:
  server:
    container_name: homelogger-server
    build: .
    ports:
      - "8083:8083"
    depends_on:
      - mongodb
    networks:
      - mongoNetwork
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/homelogger

  mongodb:
    container_name: homelogger-mongo
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mongoNetwork
    
    

volumes:
  mongo-data:

networks:
  mongoNetwork:
    driver: bridge
  